### ISSUE TITLE
Dockerfile Error

### ISSUE THREAD

**Issue by peylight** [google/ctfscoreboard#148]
Hello
Seems Dockerfile have some issue:

```
Step 10/12 : RUN python main.py createdb
 ---> Running in 51c63db01b79
Traceback (most recent call last):
  File "main.py", line 41, in <module>                                                                                                                                    
    main(sys.argv)                                                                                                                                                        
  File "main.py", line 26, in main                                                                                                                                        
    from scoreboard import wsgi                                                                                                                                           
  File "/opt/scoreboard/scoreboard/wsgi.py", line 18, in <module>                                                                                                         
    main.load_config_file(app)                                                                                                                                            
  File "/opt/scoreboard/scoreboard/main.py", line 59, in load_config_file
    app.config.from_object('config')
  File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 168, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 443, in import_string
    sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
werkzeug.utils.ImportStringError: import_string() failed for 'config'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' not found.

Original exception:

ImportError: No module named config
The command '/bin/sh -c python main.py createdb' returned a non-zero code: 1
```

**Comment by Matir** [comment]
Oh, that's unfortunate... looks like a refactoring and no longer shipping a config broke the Dockerfile.  That was a contribution, I'll have to take a look at getting it working again.
