### ISSUE TITLE
Problem trying out the project: Foreign key constraint fails

### ISSUE THREAD

**Issue by flexd** [google/ctfscoreboard#59]
I just did the basic install/setup to try this out, and happened to have a MariaDB server running (mysql) so I thought I'd try that.

I get the following error trying to add a challenge

```
Traceback (most recent call last):
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in error_router
    return self.handle_error(e)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/kristoffer/code/ctfscoreboard/scoreboard/utils.py", line 46, in wrapper
    return f(*args, **kwargs)
  File "/home/kristoffer/code/ctfscoreboard/scoreboard/utils.py", line 62, in wrapper
    return f(*args, **kwargs)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 679, in wrapper
    resp = f(*args, **kwargs)
  File "/home/kristoffer/code/ctfscoreboard/scoreboard/rest.py", line 467, in post
    models.commit()
  File "/home/kristoffer/code/ctfscoreboard/scoreboard/models.py", line 702, in commit
    db.session.commit()
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/kristoffer/code/ctfscoreboard/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
IntegrityError: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`ctfscoreboard`.`challenge`, CONSTRAINT `challenge_ibfk_1` FOREIGN KEY (`cat_slug`) REFERENCES `category` (`slug`))') [SQL: u'INSERT INTO challenge (cid, name, description, points, answer_hash, unlocked, weight, prerequisite, cat_slug) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (209040478714093, 'Test challenge', 'What is the answer to the ultimate question?', 42, '$p5k2$$8Gozsv/M$2PxSZx6pwqdfI6uzqwjdnhotEXwHqs2a', 1, 1, '', '42')]
```

Posting here before I start digging through the code, in case this is something you are aware of. :-)

**Comment by flexd** [comment]
This works perfectly fine using SQLite (which has no constraints maybe?). Not sure about Postgres.

**Comment by k9delight** [comment]
Thanks for the bug report!

We used CloudSQL for the capturetheflag.withgoogle.com event, so at least in theory it should have worked with straight MySQL. However, we have been doing a lot of development on the scoreboard lately, so it's quite possible we broke something along the way.

I'll setup MariaDB later today and try to reproduce the issue.

**Comment by k9delight** [comment]
Setup MariaDB - created database "ctfscoreboard", created database etc. Connection string is

SQLALCHEMY_DATABASE_URI = 'mysql://ctf:password@/ctfscoreboard' 

I used Debian's python-mysqldb package (instead of trying to pip install and link against mariadb specifically, to reduce moving parts). Granted the user all privileges.

`python main.py createdb` worked, so did `python main.py createdata`

I was able to create a new category fine, adding a new challenge however, gave:

IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)

IntegrityError: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`ctfscoreboard`.`challenge`, CONSTRAINT `challenge_ibfk_1` FOREIGN KEY (`cat_slug`) REFERENCES `category` (`slug`))') [SQL: u'INSERT INTO challenge (cid, name, description, points, answer_hash, unlocked, weight, prerequisite, cat_slug) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (148869166684111, 'test challenge name', 'test challenge description', 100, '$p5k2$$Zp0r/yHg$/IaoKQQOYngEyAOhomQhZq/rnpBhAEM8', 1, 26L, '', 'test challenge answer')]

where "test challenge answer" is the answer, not the category slug.

@zwade, can you take a look regarding your recent changes in this area? Thanks!

**Comment by Matir** [comment]
@k9delight Did you happen to catch the contents of the post request?

**Comment by k9delight** [comment]
Nah - turns out the problem was argument ordering to Challenge.create()

I'll talk to zwade@ about setting him up with MariaDB, and longer term once we look at CI type functionality, testing with databases that support constraints as we use them (seems as if sqlite does not support our use case).
