### ISSUE TITLE
Error on promoting user to admin

### ISSUE THREAD

**Issue by mew1033** [google/ctfscoreboard#99]
I have a game set up with Teams disabled. Another user created an account and registered and I wanted to set them up as an admin. Attempting to do so gave me an Internal Server Error. The logs showed this error:

    [2016-07-20 20:20:59,843] ERROR in app: Exception on /api/users/2 [PUT]
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 477, in wrapper
        resp = resource(*args, **kwargs)
      File "./scoreboard/utils.py", line 54, in wrapper
        return f(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
        return self.dispatch_request(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
        resp = meth(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 679, in wrapper
        resp = f(*args, **kwargs)
      File "./scoreboard/rest.py", line 138, in put
        user.team.name = data['nick']
    AttributeError: 'NoneType' object has no attribute 'name'

**Comment by k9delight** [comment]
Reassigning :)
